version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8100:80
    depends_on:
      - app
    container_name: l10_nginx

  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: l10_app

  php-cli:
    build:
      context: .
      dockerfile: _docker/php-cli/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: l10_php-cli
    tty: true

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./_db/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: l10_db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8200:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    container_name: l10_phpmyadmin

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    restart: always
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 524288000
    volumes:
      - ./_rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
    container_name: l10_rabbit
